### ISSUE TITLE
Добавить описание кейса по сбору данных

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_howto#2]
1. Заведение Веб ГИС.
2. Установка Формбилдера.
3. Подключение Веб ГИС в ФБ.
4. Создание формы.
5. Установка мобильного.
6. Передача формы на мобильный.
7. Сбор данных.

**Comment by simgislab** [comment]
может это статьей на гислаб нужно?

**Comment by BishopGIS** [comment]
Возможно. Но тут как раз к вопросы, где и как мы размещаем наши материалы.
Компромис - написать тут что-то общее, а на гис-лабе уже кейс заповедника расписать.

**Comment by BishopGIS** [comment]
В общем пока решил поменять ПМИ
